@startuml
'https://plantuml.com/sequence-diagram
!includesub style/style.puml!STYLE

title **RM0 Encoder sequence diagram**\n<i>__IVS Transcoding__</i>\n
hide unlinked

actor User

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml