/* The copyright in this software is being made available under the BSD
 * License, included below. This software may be subject to other third party
 * and contributor rights, including patent rights, and no such rights are
 * granted under this license.
 *
 * Copyright (c) 2010-2021, ISO/IEC
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *  * Neither the name of the ISO/IEC nor the names of its contributors may
 *    be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef EFFECTSEMANTIC_H
#define EFFECTSEMANTIC_H

#include <map>
#include <string>

namespace haptics::types {

enum class EffectSemantic {
  UX_Undefined = 0,
  UX_Click = 1,
  UX_DoubleClick = 2,
  UX_Success = 3,
  UX_Error = 4,
  UX_Alarm = 5,
  UX_Confirmatioon = 6,
  UX_Wrong = 7,
  UX_Ring = 8,
  UX_Message = 9,
  Avatar_Undefined = 256,
  Avatar_Jumping = 257,
  Avatar_Fall = 258,
  Avatar_Crawl = 259,
  Avatar_Swim = 260,
  Avatar_Collision = 261,
  Avatar_Grab = 262,
  Avatar_Touch = 263,
  Avatar_Swip = 264,
  Avatar_Footstep = 265,
  SpecialFX_Undefined = 512,
  SpecialFX_Washout = 513,
  SpecialFX_Noise = 514,
  WeaponCombat_Undefined = 768,
  WeaponCombat_Blade = 769,
  WeaponCombat_Hit = 770,
  WeaponCombat_HandThrown = 771,
  WeaponCombat_ElasticPropulsion = 772,
  WeaponCombat_Pneumatic = 773,
  WeaponCombat_Handgun = 774,
  WeaponCombat_Rifle = 775,
  WeaponCombat_Shotgun = 776,
  WeaponCombat_Gun = 777,
  WeaponCombat_Machinegun = 778,
  WeaponCombat_Taser = 779,
  WeaponCombat_ElectricShock = 780,
  WeaponCombat_Mine = 781,
  WeaponCombat_Missile = 782,
  WeaponCombat_Grenade = 783,
  WeaponCombat_Blast = 784,
  Ambient_Undefined = 1024,
  Ambient_Wind = 1025,
  Ambient_Heat = 1026,
  Ambient_Cold = 1027,
  Ambient_Rain = 1028,
  Ambient_Waterfall = 1029,
  Ambient_WaterDrop = 1030,
  Ambient_ElectricBuzz = 1031,
  Ambient_Ignition = 1032,
  Ambient_Cracks = 1033,
  Ambient_Earthquack = 1034,
  Ambient_Sparks = 1035,
  Ambient_Thunderbolt = 1036,
  Texture_Undefined = 1280,
  Texture_Rock = 1281,
  Texture_Gravel = 1282,
  Texture_Sand = 1283,
  Texture_Wood = 1284,
  Texture_Metal = 1285,
  Texture_Plastic = 1286,
  Vehicle_Undefined = 1536,
  Vehicle_Engine = 1537,
  Vehicle_Doors = 1538,
  Vehicle_Brake = 1539,
  Vehicle_MechanicalContraption = 1540,
  Vehicle_Drift = 1541,
  Vehicle_RoadFriction = 1542,
  Vehicle_RoadBump = 1543,
  Vehicle_Tires = 1544,
  Vehicle_AirFriction = 1545,
  Music_Undefined = 1792,
  Music_HardMaterial = 1793,
  Music_BouncyMaterial = 1794,
  Music_Pucking = 1795,
  Music_Bowing = 1796,
  Music_Striking = 1797,
  Music_BrassInstrument = 1798,
  Music_WoodWindInstrument = 1799,
};

static const std::map<std::string, EffectSemantic> stringToEffectSemantic = {
    {"UX/Undefined", EffectSemantic::UX_Undefined},
    {"UX/Click", EffectSemantic::UX_Click},
    {"UX/DoubleClick", EffectSemantic::UX_DoubleClick},
    {"UX/Success", EffectSemantic::UX_Success},
    {"UX/Error", EffectSemantic::UX_Error},
    {"UX/Alarm", EffectSemantic::UX_Alarm},
    {"UX/Confirmatioon", EffectSemantic::UX_Confirmatioon},
    {"UX/Wrong", EffectSemantic::UX_Wrong},
    {"UX/Ring", EffectSemantic::UX_Ring},
    {"UX/Message", EffectSemantic::UX_Message},
    {"Avatar/Undefined", EffectSemantic::Avatar_Undefined},
    {"Avatar/Jumping", EffectSemantic::Avatar_Jumping},
    {"Avatar/Fall", EffectSemantic::Avatar_Fall},
    {"Avatar/Crawl", EffectSemantic::Avatar_Crawl},
    {"Avatar/Swim", EffectSemantic::Avatar_Swim},
    {"Avatar/Collision", EffectSemantic::Avatar_Collision},
    {"Avatar/Grab", EffectSemantic::Avatar_Grab},
    {"Avatar/Touch", EffectSemantic::Avatar_Touch},
    {"Avatar/Swip", EffectSemantic::Avatar_Swip},
    {"Avatar/Footstep", EffectSemantic::Avatar_Footstep},
    {"SpecialFX/Undefined", EffectSemantic::SpecialFX_Undefined},
    {"SpecialFX/Washout", EffectSemantic::SpecialFX_Washout},
    {"SpecialFX/Noise", EffectSemantic::SpecialFX_Noise},
    {"WeaponCombat/Undefined", EffectSemantic::WeaponCombat_Undefined},
    {"WeaponCombat/Blade", EffectSemantic::WeaponCombat_Blade},
    {"WeaponCombat/Hit", EffectSemantic::WeaponCombat_Hit},
    {"WeaponCombat/HandThrown", EffectSemantic::WeaponCombat_HandThrown},
    {"WeaponCombat/ElasticPropulsion", EffectSemantic::WeaponCombat_ElasticPropulsion},
    {"WeaponCombat/Pneumatic", EffectSemantic::WeaponCombat_Pneumatic},
    {"WeaponCombat/Handgun", EffectSemantic::WeaponCombat_Handgun},
    {"WeaponCombat/Rifle", EffectSemantic::WeaponCombat_Rifle},
    {"WeaponCombat/Shotgun", EffectSemantic::WeaponCombat_Shotgun},
    {"WeaponCombat/Gun", EffectSemantic::WeaponCombat_Gun},
    {"WeaponCombat/Machinegun", EffectSemantic::WeaponCombat_Machinegun},
    {"WeaponCombat/Taser", EffectSemantic::WeaponCombat_Taser},
    {"WeaponCombat/ElectricShock", EffectSemantic::WeaponCombat_ElectricShock},
    {"WeaponCombat/Mine", EffectSemantic::WeaponCombat_Mine},
    {"WeaponCombat/Missile", EffectSemantic::WeaponCombat_Missile},
    {"WeaponCombat/Grenade", EffectSemantic::WeaponCombat_Grenade},
    {"WeaponCombat/Blast", EffectSemantic::WeaponCombat_Blast},
    {"Ambient/Undefined", EffectSemantic::Ambient_Undefined},
    {"Ambient/Wind", EffectSemantic::Ambient_Wind},
    {"Ambient/Heat", EffectSemantic::Ambient_Heat},
    {"Ambient/Cold", EffectSemantic::Ambient_Cold},
    {"Ambient/Rain", EffectSemantic::Ambient_Rain},
    {"Ambient/Waterfall", EffectSemantic::Ambient_Waterfall},
    {"Ambient/WaterDrop", EffectSemantic::Ambient_WaterDrop},
    {"Ambient/ElectricBuzz", EffectSemantic::Ambient_ElectricBuzz},
    {"Ambient/Ignition", EffectSemantic::Ambient_Ignition},
    {"Ambient/Cracks", EffectSemantic::Ambient_Cracks},
    {"Ambient/Earthquack", EffectSemantic::Ambient_Earthquack},
    {"Ambient/Sparks", EffectSemantic::Ambient_Sparks},
    {"Ambient/Thunderbolt", EffectSemantic::Ambient_Thunderbolt},
    {"Texture/Undefined", EffectSemantic::Texture_Undefined},
    {"Texture/Rock", EffectSemantic::Texture_Rock},
    {"Texture/Gravel", EffectSemantic::Texture_Gravel},
    {"Texture/Sand", EffectSemantic::Texture_Sand},
    {"Texture/Wood", EffectSemantic::Texture_Wood},
    {"Texture/Metal", EffectSemantic::Texture_Metal},
    {"Texture/Plastic", EffectSemantic::Texture_Plastic},
    {"Vehicle/Undefined", EffectSemantic::Vehicle_Undefined},
    {"Vehicle/Engine", EffectSemantic::Vehicle_Engine},
    {"Vehicle/Doors", EffectSemantic::Vehicle_Doors},
    {"Vehicle/Brake", EffectSemantic::Vehicle_Brake},
    {"Vehicle/MechanicalContraption", EffectSemantic::Vehicle_MechanicalContraption},
    {"Vehicle/Drift", EffectSemantic::Vehicle_Drift},
    {"Vehicle/RoadFriction", EffectSemantic::Vehicle_RoadFriction},
    {"Vehicle/RoadBump", EffectSemantic::Vehicle_RoadBump},
    {"Vehicle/Tires", EffectSemantic::Vehicle_Tires},
    {"Vehicle/AirFriction", EffectSemantic::Vehicle_AirFriction},
    {"Music/Undefined", EffectSemantic::Music_Undefined},
    {"Music/HardMaterial", EffectSemantic::Music_HardMaterial},
    {"Music/BouncyMaterial", EffectSemantic::Music_BouncyMaterial},
    {"Music/Pucking", EffectSemantic::Music_Pucking},
    {"Music/Bowing", EffectSemantic::Music_Bowing},
    {"Music/Striking", EffectSemantic::Music_Striking},
    {"Music/BrassInstrument", EffectSemantic::Music_BrassInstrument},
    {"Music/WoodWindInstrument", EffectSemantic::Music_WoodWindInstrument}};

static const std::map<EffectSemantic, std::string> effectSemanticToString = {
    {EffectSemantic::UX_Undefined, "UX/Undefined"},
    {EffectSemantic::UX_Click, "UX/Click"},
    {EffectSemantic::UX_DoubleClick, "UX/DoubleClick"},
    {EffectSemantic::UX_Success, "UX/Success"},
    {EffectSemantic::UX_Error, "UX/Error"},
    {EffectSemantic::UX_Alarm, "UX/Alarm"},
    {EffectSemantic::UX_Confirmatioon, "UX/Confirmatioon"},
    {EffectSemantic::UX_Wrong, "UX/Wrong"},
    {EffectSemantic::UX_Ring, "UX/Ring"},
    {EffectSemantic::UX_Message, "UX/Message"},
    {EffectSemantic::Avatar_Undefined, "Avatar/Undefined"},
    {EffectSemantic::Avatar_Jumping, "Avatar/Jumping"},
    {EffectSemantic::Avatar_Fall, "Avatar/Fall"},
    {EffectSemantic::Avatar_Crawl, "Avatar/Crawl"},
    {EffectSemantic::Avatar_Swim, "Avatar/Swim"},
    {EffectSemantic::Avatar_Collision, "Avatar/Collision"},
    {EffectSemantic::Avatar_Grab, "Avatar/Grab"},
    {EffectSemantic::Avatar_Touch, "Avatar/Touch"},
    {EffectSemantic::Avatar_Swip, "Avatar/Swip"},
    {EffectSemantic::Avatar_Footstep, "Avatar/Footstep"},
    {EffectSemantic::SpecialFX_Undefined, "SpecialFX/Undefined"},
    {EffectSemantic::SpecialFX_Washout, "SpecialFX/Washout"},
    {EffectSemantic::SpecialFX_Noise, "SpecialFX/Noise"},
    {EffectSemantic::WeaponCombat_Undefined, "WeaponCombat/Undefined"},
    {EffectSemantic::WeaponCombat_Blade, "WeaponCombat/Blade"},
    {EffectSemantic::WeaponCombat_Hit, "WeaponCombat/Hit"},
    {EffectSemantic::WeaponCombat_HandThrown, "WeaponCombat/HandThrown"},
    {EffectSemantic::WeaponCombat_ElasticPropulsion, "WeaponCombat/ElasticPropulsion"},
    {EffectSemantic::WeaponCombat_Pneumatic, "WeaponCombat/Pneumatic"},
    {EffectSemantic::WeaponCombat_Handgun, "WeaponCombat/Handgun"},
    {EffectSemantic::WeaponCombat_Rifle, "WeaponCombat/Rifle"},
    {EffectSemantic::WeaponCombat_Shotgun, "WeaponCombat/Shotgun"},
    {EffectSemantic::WeaponCombat_Gun, "WeaponCombat/Gun"},
    {EffectSemantic::WeaponCombat_Machinegun, "WeaponCombat/Machinegun"},
    {EffectSemantic::WeaponCombat_Taser, "WeaponCombat/Taser"},
    {EffectSemantic::WeaponCombat_ElectricShock, "WeaponCombat/ElectricShock"},
    {EffectSemantic::WeaponCombat_Mine, "WeaponCombat/Mine"},
    {EffectSemantic::WeaponCombat_Missile, "WeaponCombat/Missile"},
    {EffectSemantic::WeaponCombat_Grenade, "WeaponCombat/Grenade"},
    {EffectSemantic::WeaponCombat_Blast, "WeaponCombat/Blast"},
    {EffectSemantic::Ambient_Undefined, "Ambient/Undefined"},
    {EffectSemantic::Ambient_Wind, "Ambient/Wind"},
    {EffectSemantic::Ambient_Heat, "Ambient/Heat"},
    {EffectSemantic::Ambient_Cold, "Ambient/Cold"},
    {EffectSemantic::Ambient_Rain, "Ambient/Rain"},
    {EffectSemantic::Ambient_Waterfall, "Ambient/Waterfall"},
    {EffectSemantic::Ambient_WaterDrop, "Ambient/WaterDrop"},
    {EffectSemantic::Ambient_ElectricBuzz, "Ambient/ElectricBuzz"},
    {EffectSemantic::Ambient_Ignition, "Ambient/Ignition"},
    {EffectSemantic::Ambient_Cracks, "Ambient/Cracks"},
    {EffectSemantic::Ambient_Earthquack, "Ambient/Earthquack"},
    {EffectSemantic::Ambient_Sparks, "Ambient/Sparks"},
    {EffectSemantic::Ambient_Thunderbolt, "Ambient/Thunderbolt"},
    {EffectSemantic::Texture_Undefined, "Texture/Undefined"},
    {EffectSemantic::Texture_Rock, "Texture/Rock"},
    {EffectSemantic::Texture_Gravel, "Texture/Gravel"},
    {EffectSemantic::Texture_Sand, "Texture/Sand"},
    {EffectSemantic::Texture_Wood, "Texture/Wood"},
    {EffectSemantic::Texture_Metal, "Texture/Metal"},
    {EffectSemantic::Texture_Plastic, "Texture/Plastic"},
    {EffectSemantic::Vehicle_Undefined, "Vehicle/Undefined"},
    {EffectSemantic::Vehicle_Engine, "Vehicle/Engine"},
    {EffectSemantic::Vehicle_Doors, "Vehicle/Doors"},
    {EffectSemantic::Vehicle_Brake, "Vehicle/Brake"},
    {EffectSemantic::Vehicle_MechanicalContraption, "Vehicle/MechanicalContraption"},
    {EffectSemantic::Vehicle_Drift, "Vehicle/Drift"},
    {EffectSemantic::Vehicle_RoadFriction, "Vehicle/RoadFriction"},
    {EffectSemantic::Vehicle_RoadBump, "Vehicle/RoadBump"},
    {EffectSemantic::Vehicle_Tires, "Vehicle/Tires"},
    {EffectSemantic::Vehicle_AirFriction, "Vehicle/AirFriction"},
    {EffectSemantic::Music_Undefined, "Music/Undefined"},
    {EffectSemantic::Music_HardMaterial, "Music/HardMaterial"},
    {EffectSemantic::Music_BouncyMaterial, "Music/BouncyMaterial"},
    {EffectSemantic::Music_Pucking, "Music/Pucking"},
    {EffectSemantic::Music_Bowing, "Music/Bowing"},
    {EffectSemantic::Music_Striking, "Music/Striking"},
    {EffectSemantic::Music_BrassInstrument, "Music/BrassInstrument"},
    {EffectSemantic::Music_WoodWindInstrument, "Music/WoodWindInstrument"}};
} // namespace haptics::types
#endif
