@startjson
{
    "Metadata": {
        "Version": 0
        },
    "Vibrations": [
        {
            "EncodingModality": "Quantized: 0",
            "WindowLength": "float: ]0;x]",
            "WaveBands 0-N": [
                {
                    "Lower Frequency Limit": "float ]0; 1000]",
                    "Higher Frequency Limit": "float ]0; 1000]",
                    "Streams": [
                        {
                            "Position": "float: [0;x]",
                            "Phase": "float: [0; 2PI]",
                            "Waves": [
                                {
                                    "AmplitudeValue": "float: [-1;1]",
                                    "FrequencyValue": "float: ]0;1000]"
                                },
                                "..."
                            ]
                        },
                        "..."
                    ]
                },
                "..."
            ],
            "TransientBands 0-N": [
                {
                    "AmplitudeValue": "float: [-1;1]",
                    "FrequencyValue": "float: ]0;1000]",
                    "RelativePosition": "float: [0-x]"
                },
                "..."
            ],
            "KeyframeBands 0-N": [
                {
                    "AmplitudeValue": "float: [-1;1]",
                    "RelativePosition": "float: [0-x]"
                },
                "..."
            ]
        },
        {
            "EncodingModality": "Vectorial: 1",
            "WaveBands 0-N": [
                {
                    "Streams": [
                        {
                            "Position": "float: [0;x]",
                            "Phase": "float: [0; 2PI]",
                            "Waves": [
                                {
                                    "AmplitudeValue": "float: [-1;1]",
                                    "FrequencyValue": "float: ]0;1000]",
                                    "RelativePosition": "float: [0-x]"
                                },
                                "..."
                            ]
                        },
                        "..."
                    ]
                },
                "..."
            ],
            "TransientBands 0-N": [],
            "KeyframeBands 0-N": []
        },
        {}
    ],
    "Textures": [],
    "Stiffness": []
}
@endjson